version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
    labels:
      - dependencies
    reviewers:
      - brpaz
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directories:
      - "/"
    labels:
      - dependencies
    reviewers:
      - brpaz
    schedule:
      interval: weekly
