name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:
jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
