name: Update Changelog

on:
  release:
    types:
      - published

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # A custom PAT is required, to bypass branch protection rules
          persist-credentials: false
          token: ${{ secrets.REPO_PAT }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Set release commit message
        id: release_commit_message
        run: |
            echo "commit_message=chore(release): release: ${VERSION} [skip-ci]" >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "${{ steps.release_commit_message.outputs.commit_message }}"
          file_pattern: "CHANGELOG.md"
